### ISSUE TITLE
TypeError (on budget calculation?!)

### ISSUE THREAD

**Issue by exploide** [d120/pyBuchaktion#45] opened 2017-05-13 10:13 UTC
```
Internal Server Error: /de/studierende/buchaktion/bestellsystem/book/80/order/

TypeError at /de/studierende/buchaktion/bestellsystem/book/80/order/
unsupported operand type(s) for -: 'NoneType' and 'int'

Traceback:  

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/cms/utils/decorators.py" in inner
  18.         return func(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/pyTUID/mixins.py" in dispatch
  38.                 return super().dispatch(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/pyBuchaktion/mixins.py" in dispatch
  62.         return super(StudentContextMixin, self).dispatch(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/pyBuchaktion/mixins.py" in dispatch
  101.         response = super(NeverCacheMixin, self).dispatch(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/views/generic/edit.py" in post
  217.         return super(BaseCreateView, self).post(request, *args, **kwargs)

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/views/generic/edit.py" in post
  182.         if form.is_valid():

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/forms/forms.py" in is_valid
  169.         return self.is_bound and not self.errors

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/forms/forms.py" in errors
  161.             self.full_clean()

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/forms/forms.py" in full_clean
  371.         self._clean_form()

File "/srv/djangocms/venv/lib/python3.4/site-packages/django/forms/forms.py" in _clean_form
  398.             cleaned_data = self.clean()

File "/srv/djangocms/venv/lib/python3.4/site-packages/pyBuchaktion/forms.py" in clean
  36.         budget_left = budget_max - budget_spent

Exception Type: TypeError at /de/studierende/buchaktion/bestellsystem/book/80/order/
Exception Value: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by BluemlJ** [comment] 2017-05-13 10:42
I think "-1" as default value for books with unknown price was not my best idea.

**Comment by BluemlJ** [comment] 2017-05-13 11:01
Default value for books with unknown price is now "0"

**Comment by Xiphoseer** [comment] 2017-05-14 21:13
I don't actually think that this is the case. The log clearly says, that `budget_max` was a `NoneType`, which is loaded as an aggregate sum of the book order budget every student has available in a given timeframe. As this is queried through an existing timeframe, it should have crashed earlier if anything. So it would be nice to know when this occured, to try and reproduce it.

**Comment by schroedingersZombie** [comment] 2017-05-14 21:17
I think the error occoured when I tried to order something while @BluemlJ changed the configuration.
At least the time of the error mail matches the time I got the 500 Error

So I think this is not a bug only bad timing, i propose to close this issue

**Closed** 2017-05-15 10:39 UTC
Labels: bug, help wanted, not reproducable

**Comment by BluemlJ** [comment] 2017-05-15 11:14
Default value "-1" is not a problem
